# Jekyll configuration for GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
title: "刘浩阳 - 个人网站"
description: "刘浩阳的个人网站 - 展示我的项目作品和技术技能"
url: "https://LHY-in-universe.github.io"
baseurl: "/Liu_Haoyang_Web"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata